title: GA4GH - Metadata
label: GA4GH::Metadata
email: meta@ga4ghdata.org
github_organisation: ga4gh-metadata
future: true
navigation_categories:
  news: News
  schemablocks: SchemaBlocks
  howto: Examples & Guides
navigation_static_links:
  ga4gh:
    url: "http://ga4gh.org"
    label: "GA4GH Main Site"
  schemablocks:
    url: "http://schemablocks.org"
    label: "GA4GH SchemaBlocks"
